### ISSUE TITLE
transitionInterval not working, showPageIndicators not working

### ISSUE THREAD

**Issue by MichiMich** [shbatm/MMM-KeyBindings#1]
Hi there,

i tried out your module and installed it as mentioned. If i use your "Example - Slides Carousel" (copy-paste) it displays only the first slide and never gets to the next one. I tried also to enable the "showPageIndicators" but nothing happened. Do you think its possible to check this example and the functions? Or do i miss to install some other modules not mentioned in your ReadMe file?

Thanks and regards

Michael

**Comment by shbatm** [comment]
Moving this issue to shbatm/MMM-Carousel#1
