### ISSUE TITLE
Errors during npm installation 

### ISSUE THREAD

**Issue by Dresch360** [shbatm/MMM-KeyBindings#10]
Thanks for creating this amazing module. I hope this module is still being supported as it is incredibly useful and interactive with the Fire TV remote. Any help you can provide would be greatly appreciated - many thanks in advance. 

Here is the error after npm install:
> MMM-KeyBindings@1.3.1 preinstall /home/pi/MagicMirror/modules/MMM-KeyBindings
> ./preinstall.sh

libudev-dev is already installed. Moving on.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> evdev@0.2.5 install /home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/evdev
> node-gyp rebuild

make: Entering directory '/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/evdev/build'
  CXX(target) Release/obj.target/ioctls/src/ioctls.o
../src/ioctls.cc:10:11: error: ‘v8::Handle’ has not been declared
 using v8::Handle;
           ^~~~~~
In file included from ../../nan/nan.h:56,
                 from ../src/ioctls.cc:1:
/home/pi/.cache/node-gyp/12.18.3/include/node/node.h:608:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/12.18.3/include/node/node.h:642:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/ioctls.cc:46:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(ioctls, Init)
 ^~~~~~~~~~~
make: *** [ioctls.target.mk:109: Release/obj.target/ioctls/src/ioctls.o] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/evdev/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/evdev
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! evdev@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the evdev@0.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-02-20T21_45_18_966Z-debug.log

**Comment by nitewing76** [comment]
I have no idea what is causing your error, but I installed this an hour ago and it worked fine. Maybe something corrupted during the transfer?

**Comment by dresch27** [comment]
Thanks for your response - I'm using the latest MM version 2.14 - wondering if there is a compatibility issue.

**Comment by KristjanESPERANTO** [comment]
I have the same errors with MagicMirror v2.15.0.

**Comment by hernandosalas** [comment]
Any updates?

**Comment by KristjanESPERANTO** [comment]
PR #12 should fix this :slightly_smiling_face:

**Comment by Dresch360** [comment]
Thanks for your response. Unfortunately, freezing at npm install with the following:

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/pi/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code ETIMEDOUT
npm ERR! npm ERR! syscall connect
npm ERR! npm ERR! errno ETIMEDOUT
npm ERR! npm ERR! network request to http://10.19.101.12:4873/node-addon-api/-/node-addon-api-4.0.0.tgz failed, reason: connect ETIMEDOUT 10.19.101.12:4873
npm ERR! npm ERR! network This is a problem related to network connectivity.
npm ERR! npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! npm ERR! network 
npm ERR! npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/pi/.npm/_logs/2021-12-05T23_20_37_641Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-05T23_20_38_699Z-debug.log

**Comment by Dresch360** [comment]
> PR #12 should fix this 🙂

Thanks! This worked!

**Comment by KristjanESPERANTO** [comment]
@Dresch360: Nice :slightly_smiling_face: Can you please close this issue?
