### ISSUE TITLE
Change Pages with NumPad

### ISSUE THREAD

**Issue by Aruscha** [shbatm/MMM-KeyBindings#11]
Hello,

I would like to change the pages from the module pages via my NumPad, but somehow it doesn't quite work.
Could someone give me an example of how I would have to configure this ?

**Comment by KristjanESPERANTO** [comment]
For me it's working with the Numpad. Maybe you have to use the <kbd>Num Lock</kbd> key before.

**Comment by Alfniator** [comment]
Can I open this issue?
