### ISSUE TITLE
MMM-GoogleMapsTraffic breaks MMM-KeyBindings

### ISSUE THREAD

**Issue by rklueber** [shbatm/MMM-KeyBindings#2]
Hello,

when I enable MMM-GoogleMapsTraffic the module MMM-KeyBindings breaks. SpecialKeys are no longer executed. Cant switch on/off the screen anymore f.e. . Keys are not "forwarded" to other modules anymore. MMM-Carousel cant be controlled with the Bluetooth remote like Amazon Fire TV Remote.

Any help to debug this? much appreciated.

Regards
Ralf

**Comment by shbatm** [comment]
Strange, I'm pretty sure one of my mirrors uses both modules without issue (away and can't check right now).

Have you tried changing the loading order of the modules (e.g. change the order they are listed in the config file)?  Maybe loading the KeyBindings later would help.

Are you seeing any errors in either the server log (terminal) or web browser console (Ctrl+Shift+J)?
