### ISSUE TITLE
[Bug] Home Key activates depreciated MONITORTOGGLE

### ISSUE THREAD

**Issue by LadnerJamie** [shbatm/MMM-KeyBindings#6]
After installing the MMM-Keybindings module as per the instructions and placing the default configuration in my config.js file:

{
    module: 'MMM-KeyBindings',
    config: {
        enableMousetrap: true
    }

The "Home" key activates the MONITORTOGGLE action.

My understanding from this post [https://forum.magicmirror.builders/topic/2569/mmm-keybindings-control-your-mirror-with-amazon-fire-stick-remote-and-generic-keyboard-inputs/20] the MONITORTOGGLE will not control the monitor as all that functionality has been moved over to MMM-Remote-Control. As far as I can tell (I am definitely not a programmer) the MMM-Keybinding.js still retains a reference to MONITORTOGGLE on line 41. If I change MONTIORTOGGLE to MONITOROFF the issue seems to be resolved.

**Comment by shbatm** [comment]
The actual execution of MONITOR TOGGLE has been moved to MMM-Remote-Control, however, this module still includes the action by default. You can add `actions: []` in your config to disable the home button function.

**Comment by LadnerJamie** [comment]
After I had installed MMM-KeyBindings and entered the default configuration as mentioned above in the Magicmirror config.js I was able to see the notification on the console that MMM-KeyBindings captured the "Home" key longpress and passed the MONITORTOGGLE notification, but my monitor would not turn off. I also turned the monitor off with MMM-Remote-Control and then attempted to turn it back on with the Home key longpressed but had the same result. 

When I attempt to pass the "MONITORTOGGLE" action to MMM-Remote-Control via URL "http://192.168.1.104:8080/remote?action=MONITORTOGGLE" I recieved the error "Unknown Command".

Do I need to be using your fork of MMM-Remote-Control?

**Comment by shbatm** [comment]
Yes, you need to be using the develop branch of my fork of MMM-Remote-Control for now. I thought we'd have the integration done by now, but it hasn't been merged yet.

**Comment by LadnerJamie** [comment]
OK, thanks. I have installed your fork of MMM-Remote-Control ... I really like the idea of the api for controlling the MM.  I am still having an issue with the MONTORTOGGLE command, but it is a different one now. Let me know if you'd like me to open a separate bug report.

The "Home" key LONGPRESS is recognized as a the default MONITORTOGGLE command, which your fork of MMM-Remote-Control understands, but it seems think that my monitor is always off even if the monitor is on.

I am able to pass the URL: "http://192.168.1.104:8080/api/monitor/toggle" at which point the monitor refreshes and stays on. I get success: true, monitor "on" returned. 
Afterward if I pass "http://192.168.1.104:8080/api/monitor/status" I get success: true, monitor "off" however the monitor is still on.
If I pass "http://192.168.1.104:8080/api/monitor/off"  the monitor will turn off. 

If it is helpful, tvservice -s returns a state of 0x12000a when the monitor is on and 0x120002 when the monitor is off.

**Comment by shbatm** [comment]
Can you please let me know what the full text of `tvservice -s` is?  

For example, my Raspberry Pi 3 returns:

```shell
state 0x120002 [TV is off]  # Monitor is off
state 0x12000a [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive # Monitor is on
```

The default command looks at "TV is off" and "HDMI" for the status, but if new versions don't report the extra info, I'll update to just use the codes for status.

**Comment by LadnerJamie** [comment]
My Pi 3 returns the same when I give the 'tvservice -s' command

'state 0x120002 [TV is off]' when my monitor has been turned off (http://magicmirrorip:8080/api/montior/off)
'state 0x12000a [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive' when my monitor has been turned on (http://magicmirrorip:8080/api/montior/toggle)

Strange that it seems to return the same info, yet for some reason it doesn't recognize that my monitor is on. Would the DevTools help in this situation, or is there some way that I could troubleshoot further?

**Comment by shbatm** [comment]
I'm not sure why it's reporting the wrong status.  Is it functioning correctly and just reporting the wrong status (e.g. is TOGGLE turning it on and off when it is supposed to)?

You can try adding this in your config for MMM-Remote-Control, it will override the default status command.  Just to see if it does the same thing:

```js
customCommand: {
    monitorStatusCommand: `if [ $(tvservice -s | cut -d ' ' -f 2 ) = "0x12000a" ]; then echo "true"; else echo "false"; fi`
}
```

It sounds like the MM code is functioning so I don't know if there would be any errors, but it's always good to check.  If you're using the default installation of MM, you can watch the console logs by running `pm2 logs mm` in an SSH session while you turn on/off the monitor and see what happens.  DevTools is the browser console, which can be opened by pressing `Ctrl+Shift+I` on the Mirror's screen (requires a keyboard hooked up to the mirror).  You can also start the DevTools window manually with MM by stopping MM, and then starting it with `cd ~/MagicMirror/ && npm start dev`.

**Comment by LadnerJamie** [comment]
OK, I have added the customCommand into my config for MMM-Remote-Control.  I think I may have erred on the "too much information" side below, hopfully it will be helpful. For some reason monitorstatus seems to return the opposite of whatever the monitor status actually is, even though your customcommand in my config returns the correct status.  Let me know if I can provide any more info.

Fresh reboot, MM autostarts with pm2, monitor is currently on and displaying MM.

- I SSH in and issue tvservice -s |cut -d ' ' -f 2  and receive
`0x12000a`
- I enter "http://192.168.1.104:8080/api/monitor/status" and receive "success: true, monitor: off"
but receive "true" in the pm2 log.
- If I then enter "http://192.168.1.104:8080/api/monitor/toggle", I receive "success: true, monitor: on" The monitor 'refreshes' ie. blinks off for a second and then comes back on.
- The log says "Powering on HDMI with preferred settings"
- I issue tvservice -s |cut -d ' ' -f 2  and receive
`0x12000a`
- I enter "http://192.168.1.104:8080/api/monitor/status" and receive "success: true, monitor: off" in the browser, but receive "true" in the pm2 log.
- I enter "http://192.168.1.104:8080/api/monitor/off" and receive "success: true, monitor: off" in the browser, and receive "Powering off HDMI" in the pm2 log.
- The monitor turns off
- I enter "http://192.168.1.104:8080/api/monitor/status" and receive "success: true, monitor: on" in the browser, but receive "false" the pm2 log.
- I enter "http://192.168.1.104:8080/api/monitor/toggle" and receive "success: true, monitor: off" in the browser, but receive "Powering off HDMI" the pm2 log.
- I enter "http://192.168.1.104:8080/api/monitor/on" and receive "success: true, monitor: on" in the browser, and receive "Powering on HDMI with preferred settings" the pm2 log.
- I enter "http://192.168.1.104:8080/api/monitor/status" and receive "success: true, monitor: off" in the browser, but receive "true" the pm2 log.

**Comment by shbatm** [comment]
I haven't had a chance to take a look at this. I will try in the next week. I've moved the issue to MMM-Remote-Control since the issue with MMM-KeyBindings has been resolved.
