### ISSUE TITLE
[Bug] Only the "Home" Key LONGPRESSED sends notifications

### ISSUE THREAD

**Issue by LadnerJamie** [shbatm/MMM-KeyBindings#7]
I have MMM-Keybindings installed as per the documentation and have my Bluetooth Amazon TV Remote working. 

As per my previous bug submission, I am able to use the REMOTE_ACTION notification to turn my monitor on or off if I change the payload action for the  "Home" key using the "KEY_LONGPRESSED" state in MMM-Keybinding.js .  

Also if I add the following to my Magicmirror config.js I am also able to the the "Home" key KEY_LONGPRESSED state to achieve a successful MONITOROFF or MONITORON notification.
actions: [{
            key: "Home",
            state: "KEY_LONGPRESSED",
            instance: "SERVER",
            mode: "DEFAULT",
            notification: "REMOTE_ACTION",
            payload: { action: "MONITORON" }  
}

However if I add another key such as "Enter" or "ArrowLeft" or the alternate state "KEY_PRESSED" for the "Home" key MMM-Keybindings does not appear to send a notification. I have tried entering the additional configuration in the MMM-Keybindings.js as well as the Magicmirror config.js. 

I have not been successful getting other payload actions to complete successfully such as the HIDE command for MMM-Remote-Control, but I belive that may be due to syntax errors on my part. See my forum post [**here**](https://forum.magicmirror.builders/topic/2569/mmm-keybindings-control-your-mirror-with-amazon-fire-stick-remote-and-generic-keyboard-inputs/22)  for more information.

**Comment by shbatm** [comment]
I'll look at this when I get a chance today.

**Comment by shbatm** [comment]
I wasn't able to replicate the problem.  The following config worked as expected...

```js
        {
            module: 'MMM-KeyBindings',
            config: {
                actions: [{
                    key: "ArrowLeft",
                    state: "KEY_PRESSED",
                    instance: "SERVER",
                    mode: "DEFAULT",
                    notification: "REMOTE_ACTION",
                    payload: { action: "MONITORTOGGLE" }
                }]
            }
        },
```

Are you getting any errors in the console or DevTools logs when you change this?

**Comment by LadnerJamie** [comment]
OK, so I've copied your config into mine and when I do, the left arrow button calls the MONITORTOGGLE action. But the Home key LONGPRESSS no longer calls any action (although it is still specified in the MMM-Keybindings.js.

If I add the following to my config.js 
`{
            module: 'MMM-KeyBindings',
            config: {
                actions: [{
                    key: "ArrowLeft",
                    state: "KEY_PRESSED",
                    instance: "SERVER",
                    mode: "DEFAULT",
                    notification: "REMOTE_ACTION",
                    payload: { action: "MONITORTOGGLE" }
				},
	  {	    key: "Home",
                    state: "KEY_PRESSED",
                    instance: "SERVER",
                    mode: "DEFAULT",
                    notification: "REMOTE_ACTION",
                    payload: { action: "MONITORON" },
			},
          {         key: "Home",
                    state: "KEY_LONGPRESSED",
                    instance: "SERVER",
                    mode: "DEFAULT",
                    notification: "REMOTE_ACTION",
                    payload: { action: "MONITOROFF" }
                }]
            }
        },`
Then the console returns "KEY_LEFT pressed." "Powering on HDMI with preferred settings"  when I press the left arrow.
 
I also get "KEY_HOMEPAGE pressed." "Powering on HDMI with preferred settings" when I press the Home key.

But I get "KEY_HOMEPAGE long pressed." with the long press of the Home key and nothing else. 

The monitor does not turn off in any of the above instances. 

I'm not sure how to get any info from (or what are the) DevTools but I'm happy to provide more information if you can guide me to how to use the DevTools.

**Comment by shbatm** [comment]
> although it is still specified in the MMM-Keybindings.js.
Just FYI, anything specified in a modules' config section in your `config.js` file will override the defaults in a modules' `Module-Name.js` file.  So if you want the "Home" function with another function, you'll have to include it in your `config.js`.

The issue with KEY_PRESSED and KEY_LONGPRESSED required a fix. The module only looked up the first "Home" key action, and since it didn't match KEY_LONGPRESSED it was ignoring it.  I just pushed an update which will allow multiple assignments to the same key.  Please update the module and test.

To update:
```shell
cd ~/MagicMirror/modules/MMM-KeyBindings"
git pull
pm2 restart mm
```

**Comment by LadnerJamie** [comment]
Fantastic! 
Yes, this update solved the problem. I have expanded my config.js to include KEY_PRESSED and KEY_LONGPRESSED for the "home" button and the "ArrowRight" button and it is working as expected.

Thank you so much, I appreciate you taking the time to look into this.
